"""add monthly_targets.updated_at

Revision ID: 30c0f364a948
Revises: f47d7bf86b98
Create Date: 2026-07-30 13:41:43.294529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30c0f364a948'
down_revision: Union[str, Sequence[str], None] = 'f47d7bf86b98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthly_targets', sa.Column('updated_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monthly_targets', 'updated_at')
    # ### end Alembic commands ###
