"""initial schema

Revision ID: f47d7bf86b98
Revises: 
Create Date: 2026-07-30 10:53:24.468029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f47d7bf86b98'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('whoop_recovery_pct', sa.Float(), nullable=True),
    sa.Column('whoop_hrv_ms', sa.Float(), nullable=True),
    sa.Column('whoop_rhr_bpm', sa.Integer(), nullable=True),
    sa.Column('whoop_strain', sa.Float(), nullable=True),
    sa.Column('whoop_sleep_hours', sa.Float(), nullable=True),
    sa.Column('hrv_30d_avg_ms', sa.Float(), nullable=True),
    sa.Column('muscle_soreness', sa.Integer(), nullable=True),
    sa.Column('subjective_energy', sa.Integer(), nullable=True),
    sa.Column('sleep_quality_felt', sa.Integer(), nullable=True),
    sa.Column('health_check_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('monthly_targets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('month_start_date', sa.String(), nullable=False),
    sa.Column('periodisation_phase', sa.Enum('BASE', 'BUILD', 'PEAK', 'TAPER', 'RECOVERY', name='periodisation_phase', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('load_target_total', sa.Float(), nullable=True),
    sa.Column('load_actual_total', sa.Float(), nullable=True),
    sa.Column('hrv_trend_json', sa.Text(), nullable=True),
    sa.Column('race_date', sa.String(), nullable=True),
    sa.Column('month_summary_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month_start_date')
    )
    op.create_table('oauth_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.Enum('WHOOP', 'STRAVA', name='oauth_provider', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider')
    )
    op.create_table('weekly_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('week_start_date', sa.String(), nullable=False),
    sa.Column('planned_sessions_json', sa.Text(), nullable=True),
    sa.Column('adapted_plan_json', sa.Text(), nullable=True),
    sa.Column('load_target', sa.Float(), nullable=True),
    sa.Column('load_actual', sa.Float(), nullable=True),
    sa.Column('skipped_sessions', sa.Text(), nullable=True),
    sa.Column('week_status', sa.Enum('ON_TRACK', 'LOAD_DEFICIT', 'RECOVERY_WEEK', 'COMPLETE', name='week_status', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_start_date')
    )
    op.create_table('activities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('strava_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=True),
    sa.Column('intended_session_type', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('distance_metres', sa.Float(), nullable=True),
    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('avg_hr_bpm', sa.Integer(), nullable=True),
    sa.Column('max_hr_bpm', sa.Integer(), nullable=True),
    sa.Column('avg_pace_sec_per_km', sa.Float(), nullable=True),
    sa.Column('grade_adj_pace', sa.Float(), nullable=True),
    sa.Column('load_score', sa.Float(), nullable=True),
    sa.Column('rpe', sa.Integer(), nullable=True),
    sa.Column('strava_raw_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['date'], ['daily_metrics.date'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strava_id')
    )
    op.create_table('decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('scheduled_session', sa.String(), nullable=True),
    sa.Column('recommendation', sa.Enum('GO', 'MODIFY', 'MODALITY_SWAP', 'ABORT', name='decision_recommendation', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('rationale_json', sa.Text(), nullable=True),
    sa.Column('llm_explanation', sa.Text(), nullable=True),
    sa.Column('athlete_override', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['date'], ['daily_metrics.date'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_zones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('max_hr_bpm', sa.Integer(), nullable=True),
    sa.Column('rest_hr_bpm', sa.Integer(), nullable=True),
    sa.Column('zone1_min', sa.Integer(), nullable=True),
    sa.Column('zone1_max', sa.Integer(), nullable=True),
    sa.Column('zone2_min', sa.Integer(), nullable=True),
    sa.Column('zone2_max', sa.Integer(), nullable=True),
    sa.Column('zone3_min', sa.Integer(), nullable=True),
    sa.Column('zone3_max', sa.Integer(), nullable=True),
    sa.Column('zone4_min', sa.Integer(), nullable=True),
    sa.Column('zone4_max', sa.Integer(), nullable=True),
    sa.Column('zone5_min', sa.Integer(), nullable=True),
    sa.Column('zone5_max', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['date'], ['daily_metrics.date'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('activity_id', sa.String(), nullable=False),
    sa.Column('execution_score', sa.Float(), nullable=True),
    sa.Column('time_in_zone_pct', sa.Float(), nullable=True),
    sa.Column('hr_drift_coeff', sa.Float(), nullable=True),
    sa.Column('overpush_flag', sa.Boolean(), nullable=True),
    sa.Column('underpush_flag', sa.Boolean(), nullable=True),
    sa.Column('score_breakdown_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_scores')
    op.drop_table('hr_zones')
    op.drop_table('decisions')
    op.drop_table('activities')
    op.drop_table('weekly_plans')
    op.drop_table('oauth_tokens')
    op.drop_table('monthly_targets')
    op.drop_table('daily_metrics')
    # ### end Alembic commands ###
